baseURL = "https://hugo-untuk-profile.netlify.app/"
languageCode = "en-us"
summaryLength = "10"
theme = "pemro-kross-hugo"
title = "Lab Pemrograman"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[params]
address = "Kampus Tegalboto, Jl. Kalimantan No.37, Krajan Timur, Sumbersari, Kec. Sumbersari, Kabupaten Jember, Jawa Timur 68121"
author = "Lab Pemrograman"
copyright = "Copyright &copy; 2021 a theme by [Lab Pemrograman](https://gethugothemes.com)"
description = "Modifikasi dari kross-hugo"
email = "pemro@cs.unej.ac.id"
google_analytics_id = ""
home = "Home"
logo = ""
phone = "+62 331 326911"
theme_color = "#292940"
[params.contact]
enable = false
form_action = "#"
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://pemro.id/discord"
icon = "ti-discord"
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "https://instagram.com/pemroilkom_unej"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
